version: 2
multi-ecosystem-groups:
  weekly:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "weekly"